### ISSUE TITLE
Unable to run code file in windows

### ISSUE THREAD

**Issue by nehagour** [dasec/unlinkability-metric#1]
I am using spyder from anaconda environment to run evaluateUnlinkability.py in windows. this is the error I am facing

runfile('C:/Users/Neha/Desktop/unlinkability-metric-master/evaluateUnlinkability.py', wdir='C:/Users/Neha/Desktop/unlinkability-metric-master')
usage: evaluateUnlinkability.py [-h] [--omega [OMEGA]] [--nBins [NBINS]]
                                [--figureTitle [FIGURETITLE]]
                                [--legendLocation [LEGENDLOCATION]]
                                matedScoresFile nonMatedScoresFile
evaluateUnlinkability.py: error: the following arguments are required: matedScoresFile, nonMatedScoresFile
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\Users\Neha\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

kindly instruct how to run code in this repository.

**Comment by mgbarrero** [comment]
Hi @nehagour ,

it looks like you may have called the script with no arguments?

As it says in the help line code, you need to provide the following:

> evaluateUnlinkability.py: error: the following arguments are required: matedScoresFile, nonMatedScoresFile

In particular, you need to enter the path to the files containing the scores to be analysed. Two examples of how these files should look like are also included in the repo

**Comment by nehagour** [comment]
Can I run this code in windows? how can I pass arguments?
