### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by 0tist** [dasec/unlinkability-metric#2]
the matedScores.hdf5 and nonMatedScores.hdf5 scores aren't loading in the jupyter notebook, i have tried cloning the repo, downloading the file with the 'Download' button and downloaded the zip file file of the repo.
The code I am using to open the files:

`with h5py.File('matedScores.hdf5', 'r+') as f: `
`   print(f"keys: {f.keys()}")`

**Comment by jayesh0vasudeva** [comment]
`
with h5py.File('matedScores.hdf5', 'r+') as f:
    print("Keys: %s" % f.keys())
    a_group_key = list(f.keys())[0]

    # Get the data
    data = list(f[a_group_key])
`

**Comment by 0tist** [comment]
using `numpy.fromfile('matedScores.hdf5')` solves the issue.
